/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SignUpVerifyRouteImport } from './routes/sign-up/verify'
import { Route as PAliasRouteImport } from './routes/p/$alias'
import { Route as DevChatRouteImport } from './routes/dev/chat'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppMatchesRouteImport } from './routes/app/matches'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminDisputesRouteImport } from './routes/admin/disputes'
import { Route as AppServicesIndexRouteImport } from './routes/app/services/index'
import { Route as AppChatIndexRouteImport } from './routes/app/chat/index'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignUpRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SignUpVerifyRoute = SignUpVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => SignUpRoute,
} as any)
const PAliasRoute = PAliasRouteImport.update({
  id: '/p/$alias',
  path: '/p/$alias',
  getParentRoute: () => rootRouteImport,
} as any)
const DevChatRoute = DevChatRouteImport.update({
  id: '/dev/chat',
  path: '/dev/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRouteWithChildren
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/billing': typeof AppBillingRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/dev/chat': typeof DevChatRoute
  '/p/$alias': typeof PAliasRoute
  '/sign-up/verify': typeof SignUpVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/services/': typeof AppServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/billing': typeof AppBillingRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/dev/chat': typeof DevChatRoute
  '/p/$alias': typeof PAliasRoute
  '/sign-up/verify': typeof SignUpVerifyRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/app/chat': typeof AppChatIndexRoute
  '/app/services': typeof AppServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRouteWithChildren
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/billing': typeof AppBillingRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/dev/chat': typeof DevChatRoute
  '/p/$alias': typeof PAliasRoute
  '/sign-up/verify': typeof SignUpVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/services/': typeof AppServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/demo'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/admin/disputes'
    | '/admin/users'
    | '/app/billing'
    | '/app/matches'
    | '/app/profile'
    | '/app/settings'
    | '/dev/chat'
    | '/p/$alias'
    | '/sign-up/verify'
    | '/admin/'
    | '/app/'
    | '/sign-up/'
    | '/app/chat/'
    | '/app/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo'
    | '/onboarding'
    | '/sign-in'
    | '/admin/disputes'
    | '/admin/users'
    | '/app/billing'
    | '/app/matches'
    | '/app/profile'
    | '/app/settings'
    | '/dev/chat'
    | '/p/$alias'
    | '/sign-up/verify'
    | '/admin'
    | '/app'
    | '/sign-up'
    | '/app/chat'
    | '/app/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/demo'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/admin/disputes'
    | '/admin/users'
    | '/app/billing'
    | '/app/matches'
    | '/app/profile'
    | '/app/settings'
    | '/dev/chat'
    | '/p/$alias'
    | '/sign-up/verify'
    | '/admin/'
    | '/app/'
    | '/sign-up/'
    | '/app/chat/'
    | '/app/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRouteWithChildren
  DevChatRoute: typeof DevChatRoute
  PAliasRoute: typeof PAliasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sign-up/verify': {
      id: '/sign-up/verify'
      path: '/verify'
      fullPath: '/sign-up/verify'
      preLoaderRoute: typeof SignUpVerifyRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/p/$alias': {
      id: '/p/$alias'
      path: '/p/$alias'
      fullPath: '/p/$alias'
      preLoaderRoute: typeof PAliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/chat': {
      id: '/dev/chat'
      path: '/dev/chat'
      fullPath: '/dev/chat'
      preLoaderRoute: typeof DevChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matches': {
      id: '/app/matches'
      path: '/matches'
      fullPath: '/app/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/services/': {
      id: '/app/services/'
      path: '/services'
      fullPath: '/app/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/': {
      id: '/app/chat/'
      path: '/chat'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDisputesRoute: AdminDisputesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppMatchesRoute: typeof AppMatchesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppMatchesRoute: AppMatchesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SignUpRouteChildren {
  SignUpVerifyRoute: typeof SignUpVerifyRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpVerifyRoute: SignUpVerifyRoute,
  SignUpIndexRoute: SignUpIndexRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRouteWithChildren,
  DevChatRoute: DevChatRoute,
  PAliasRoute: PAliasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
